### ISSUE TITLE
Routes get refreshed every time you click a link

### ISSUE THREAD

**Issue by RichardHpa** [satansdeer/react-query-3#5]
There is an issue with StyledLink and react-router-dom that doesn't help demo React-query as well as it should.
When you click on a link that uses StyledLink, it refreshes the entire page rather than changes the route within the router. This means that react query isn't being utilised as well as it could be.

If you add in the react-query dev tools you will notice that when you change the page, the cache from the previous page gets removed. This means that each time you go onto a page a new instance of that query cache gets created rather than using what is in the cache.

I created a PR which resolves this issue.
https://github.com/satansdeer/react-query-3/pull/4

**Comment by RichardHpa** [comment]
I created a PR which resolves this issue
https://github.com/satansdeer/react-query-3/pull/4

**Comment by satansdeer** [comment]
Great job Richard 👍 

I'm gonna merge the PR now
